---
root: true
env:
  browser: true
  es6: true
  node: true
  jest: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - '@react-native-community'
  - plugin:react-native/all
  - plugin:jest/recommended
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
  project: './tsconfig.json'
plugins:
  - react
  - react-hooks
  - react-native
  - jest
  - '@typescript-eslint'
settings:
  react:
    version: detect
rules:
  linebreak-style: 0
  arrow-parens: 0
  no-shadow: warn
  no-unused-vars: warn
  max-len:
    - warn
    - 120
  object-shorthand: 0
  import/no-unresolved: off
  import/extensions: off
  react/jsx-one-expression-per-line: off
  react/jsx-props-no-spreading: off
  react/no-array-index-key: warn
  react/no-unescaped-entities: off
  react/prop-types:
    - error
    - ignore:
        - children
        - match
  react/jsx-filename-extension:
    - 1
    - extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
  react-native/no-raw-text: off
  react-native/sort-styles: off
  object-curly-newline: 0
